#pragma once

#define SHUHAI_GRPC_VERSION_MAJOR 0
#define SHUHAI_GRPC_VERSION_MINOR 2
#define SHUHAI_GRPC_VERSION_PATCH 0

#define SHUHAI_GRPC_VERSION_NUMBER \
    (SHUHAI_GRPC_VERSION_MAJOR * 10000 + SHUHAI_GRPC_VERSION_MINOR * 100 + SHUHAI_GRPC_VERSION_PATCH)

#define SHUHAI_GRPC_VERSION "0.2.0"
